baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Francisco Mendonca's Blog"
theme = ['hugo-notice', 'PaperMod']


[params]
env = "production"
description = "Francisco's blog about stuff..."
author = "Francisco Mendonca"
defaultTheme = "auto"
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
custom_css = ["css/style.css"]


[params.homeInfoParams]
Title = "Francisco Mendonca"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/QuietSwami"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false  # Set to false to disable guessing language
    highlightLines = true
    noClasses = false   # Set to false to use CSS classes for styling

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[menu.main]]
name = "Search"
url = "search/"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10

