baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Francisco Mendonca's Blog"
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Francisco Mendonca"
Content = "Can be Info, links, about..."

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/QuietSwami"

